[package]
name = "dingding"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0"
reqwest = { version = "0.11", features = ["json"] }
lettre = "0.10.0-rc.2"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }